### ISSUE TITLE
Part 1: Get all tickers of all S&P 500

### ISSUE THREAD

**Issue by dongxulee** [QuantLee/GoogleFinanceWebApp#2]
- [x] Vitual environment setup, create the
- [x] Analyzing stock tickers info on wiki page: https://en.wikipedia.org/wiki/List_of_S%26P_500_companies.
- [x] Using BeautifulSoup to extract tickers from the wiki page.
- [x] Processing the ticker data we get and make sure they are in the right format and store them in the csv file.

**Comment by aerenchyma** [comment]
You mention storing data in a CSV file here. Are you going to store in a CSV file and then a database table? Might it make sense to insert data directly into a database?

**Comment by dongxulee** [comment]
Yes, you are right, I will make changes to that soon.

**Comment by dongxulee** [comment]
Hi Jackie, Can I view this storing csv file as a caching process? And If I use pickle to store all the tickers for stock, does that count as a caching process?

**Comment by aerenchyma** [comment]
There are lots of *possible* ways to deal with caching, but I would expect either JSON files or pickling (that's fine, if that's how you want to manage it!) to be a better structure for data in a caching process. Any caching process (for this course) must store ALL the data you need from the internet request so you don't need to make it again. (Like the examples we've had in lecture and section exercises.) My comment from before referred to how you were going to deal with the database overall.
