### ISSUE TITLE
Part 3: Database setup and conduct data query test

### ISSUE THREAD

**Issue by dongxulee** [QuantLee/GoogleFinanceWebApp#4]
- [x] Design the database structure.
- [x] Database setup, extract date through googlefinance.client and store them in the database.
- [x] Query testing, make sure the data is in the right format and take a brief look at the table created through pgadmin interface.

**Comment by aerenchyma** [comment]
This sounds like an interesting project, but I'd like to see more details about how you're going to set up and arrange your database! What entities are involved in the project? What will your database tables be? What fields will be on each table?

**Comment by dongxulee** [comment]
I will add more changes to this soon, professor
